Repository apple/swift-nio-extras, pull requests merged in 2020-07, with the labels that each got.

#93 Support decompression of HTTP responses that do not contain a Content…
  Sources/NIOHTTPCompression/HTTPDecompression.swift
  Sources/NIOHTTPCompression/HTTPRequestDecompressor.swift
  Sources/NIOHTTPCompression/HTTPResponseDecompressor.swift
  Tests/NIOHTTPCompressionTests/HTTPResponseDecompressorTest+XCTest.swift
  Tests/NIOHTTPCompressionTests/HTTPResponseDecompressorTest.swift
Labels: 🔼 needs-minor-version-bump

#96 Fix #file warnings
  Tests/NIOExtrasTests/WritePCAPHandlerTest.swift
  Tests/NIOHTTPCompressionTests/HTTPResponseCompressorTest.swift
Labels: patch-version-bump-only

#97 Silence #file warnings
  Tests/NIOExtrasTests/WritePCAPHandlerTest.swift
  Tests/NIOHTTPCompressionTests/HTTPResponseCompressorTest.swift
Labels: needs-no-version-bump

#100 Ensures gzip/deflate-compressed responses are properly finalized in all cases
  Sources/NIOHTTPCompression/HTTPResponseCompressor.swift
  Tests/NIOHTTPCompressionTests/HTTPResponseCompressorTest+XCTest.swift
  Tests/NIOHTTPCompressionTests/HTTPResponseCompressorTest.swift
Labels: patch-version-bump-only
