Repository apple/swift-nio-extras, pull requests merged in 2021-06, with the labels that each got.

#129 Add Swift 5.5 nightly configuration
  docker/docker-compose.2004.55.yaml
Labels: needs-no-version-bump

#128 Implement a SOCKSv5 client
  Package.swift
  Sources/NIOSOCKS/Channel Handlers/SOCKSClientHandler.swift
  Sources/NIOSOCKS/Messages/AuthenticationMethod.swift
  Sources/NIOSOCKS/Messages/ClientGreeting.swift
  Sources/NIOSOCKS/Messages/Errors.swift
  Sources/NIOSOCKS/Messages/Helpers.swift
  Sources/NIOSOCKS/Messages/SOCKSRequest.swift
  Sources/NIOSOCKS/Messages/SOCKSResponse.swift
  Sources/NIOSOCKS/Messages/SelectedAuthenticationMethod.swift
  Sources/NIOSOCKS/State/ClientStateMachine.swift
  Sources/NIOSOCKSClient/main.swift
  Tests/LinuxMain.swift
  Tests/NIOSOCKSTests/ClientGreeting+Tests+XCTest.swift
  Tests/NIOSOCKSTests/ClientGreeting+Tests.swift
  Tests/NIOSOCKSTests/ClientRequest+Tests+XCTest.swift
  Tests/NIOSOCKSTests/ClientRequest+Tests.swift
  Tests/NIOSOCKSTests/ClientStateMachine+Tests+XCTest.swift
  Tests/NIOSOCKSTests/ClientStateMachine+Tests.swift
  Tests/NIOSOCKSTests/Helpers+Tests+XCTest.swift
  Tests/NIOSOCKSTests/Helpers+Tests.swift
  Tests/NIOSOCKSTests/MethodSelection+Tests+XCTest.swift
  Tests/NIOSOCKSTests/MethodSelection+Tests.swift
  Tests/NIOSOCKSTests/ServerResponse+Tests+XCTest.swift
  Tests/NIOSOCKSTests/ServerResponse+Tests.swift
  Tests/NIOSOCKSTests/SocksClientHandler+Tests+XCTest.swift
  Tests/NIOSOCKSTests/SocksClientHandler+Tests.swift
Labels: 🔼 needs-minor-version-bump

#131 Fix SOCKS client sending greeting and port/address endianness
  Sources/NIOSOCKS/Channel Handlers/SOCKSClientHandler.swift
  Sources/NIOSOCKS/Messages/SOCKSRequest.swift
  Sources/NIOSOCKSClient/main.swift
  Tests/NIOSOCKSTests/ClientRequest+Tests.swift
  Tests/NIOSOCKSTests/SocksClientHandler+Tests+XCTest.swift
  Tests/NIOSOCKSTests/SocksClientHandler+Tests.swift
Labels: patch-version-bump-only

#133 Fix incorrect SOCKS client flushing behaviour
  Sources/NIOSOCKS/Channel Handlers/SOCKSClientHandler.swift
  Tests/NIOSOCKSTests/SocksClientHandler+Tests+XCTest.swift
  Tests/NIOSOCKSTests/SocksClientHandler+Tests.swift
Labels: patch-version-bump-only

#134 Add SOCKS authentication fast path
  Sources/NIOSOCKS/Channel Handlers/SOCKSServerHandshakeHandler.swift
  Sources/NIOSOCKS/State/ServerStateMachine.swift
  Tests/NIOSOCKSTests/SOCKSServerHandshakeHandler+Tests+XCTest.swift
  Tests/NIOSOCKSTests/SOCKSServerHandshakeHandler+Tests.swift
  Tests/NIOSOCKSTests/ServerStateMachine+Tests.swift
Labels: patch-version-bump-only

#136 Add SOCKSProxyEstablishedEvent
  Sources/NIOSOCKS/Channel Handlers/SOCKSClientHandler.swift
  Sources/NIOSOCKS/Channel Handlers/SOCKSServerHandshakeHandler.swift
  Tests/NIOSOCKSTests/SOCKSServerHandshakeHandler+Tests.swift
  Tests/NIOSOCKSTests/SocksClientHandler+Tests+XCTest.swift
  Tests/NIOSOCKSTests/SocksClientHandler+Tests.swift
Labels: 🔼 needs-minor-version-bump

#138 Remove support for Swift 5.0 and 5.1
  Package.swift
  README.md
  docker/Dockerfile
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.52.yaml
  scripts/check_no_api_breakages.sh
Labels: 🔼 needs-minor-version-bump

#139 Update NIO dependency to 2.30.0
  Package.swift
  README.md
Labels: patch-version-bump-only
