Repository apple/swift-nio-extras, pull requests merged in 2022-08, with the labels that each got.

#168 Deprecate cumulationBuffer
  Sources/NIOExtras/FixedLengthFrameDecoder.swift
  Sources/NIOExtras/LengthFieldBasedFrameDecoder.swift
  Sources/NIOExtras/LineBasedFrameDecoder.swift
Labels: patch-version-bump-only

#169 Docnioextras
  Sources/NIOExtras/DebugInboundEventsHandler.swift
  Sources/NIOExtras/DebugOutboundEventsHandler.swift
  Sources/NIOExtras/Docs.docc/Article.md
  Sources/NIOExtras/FixedLengthFrameDecoder.swift
  Sources/NIOExtras/JSONRPCFraming+ContentLengthHeader.swift
  Sources/NIOExtras/JSONRPCFraming.swift
  Sources/NIOExtras/LengthFieldBasedFrameDecoder.swift
  Sources/NIOExtras/LengthFieldPrepender.swift
  Sources/NIOExtras/LineBasedFrameDecoder.swift
  Sources/NIOExtras/NIOExtrasError.swift
  Sources/NIOExtras/NIOLengthFieldBitLength.swift
  Sources/NIOExtras/PCAPRingBuffer.swift
  Sources/NIOExtras/QuiescingHelper.swift
  Sources/NIOExtras/RequestResponseHandler.swift
  Sources/NIOExtras/WritePCAPHandler.swift
  Sources/NIOHTTPCompression/HTTPCompression.swift
  Sources/NIOHTTPCompression/HTTPDecompression.swift
  Sources/NIOHTTPCompression/HTTPRequestCompressor.swift
  Sources/NIOHTTPCompression/HTTPRequestDecompressor.swift
  Sources/NIOHTTPCompression/HTTPResponseCompressor.swift
  Sources/NIOHTTPCompression/HTTPResponseDecompressor.swift
  Sources/NIOSOCKS/Channel Handlers/SOCKSClientHandler.swift
  Sources/NIOSOCKS/Channel Handlers/SOCKSServerHandshakeHandler.swift
  Sources/NIOSOCKS/Messages/ClientGreeting.swift
  Sources/NIOSOCKS/Messages/SOCKSRequest.swift
  Sources/NIOSOCKS/Messages/SOCKSResponse.swift
  Sources/NIOSOCKS/Messages/SelectedAuthenticationMethod.swift
Labels: needs-no-version-bump

#170 Simple index pages for docc
  Sources/NIOExtras/Docs.docc/Article.md
  Sources/NIOExtras/Docs.docc/index.md
  Sources/NIOExtras/WritePCAPHandler.swift
  Sources/NIOHTTPCompression/Docs.docc/index.md
  Sources/NIOHTTPCompression/HTTPDecompression.swift
  Sources/NIOSOCKS/Docs.docc/index.md
Labels: needs-no-version-bump

#171 Validate missing imports in CI
  docker/docker-compose.2004.main.yaml
  docker/docker-compose.yaml
Labels: needs-no-version-bump

#173 Adopt `Sendable` in `NIOSOCKS`
  Sources/NIOSOCKS/Channel Handlers/SOCKSClientHandler.swift
  Sources/NIOSOCKS/Channel Handlers/SOCKSServerHandshakeHandler.swift
  Sources/NIOSOCKS/Messages/AuthenticationMethod.swift
  Sources/NIOSOCKS/Messages/ClientGreeting.swift
  Sources/NIOSOCKS/Messages/Messages.swift
  Sources/NIOSOCKS/Messages/SOCKSRequest.swift
  Sources/NIOSOCKS/Messages/SOCKSResponse.swift
  Sources/NIOSOCKS/Messages/SelectedAuthenticationMethod.swift
Labels: 🔼 needs-minor-version-bump
