Repository apple/swift-nio-extras, pull requests merged in 2024-03, with the labels that each got.

#218 Raise minimum swift version to 5.8
  Package.swift
  README.md
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.57.yaml
Labels: 🔼 needs-minor-version-bump

#220 Fixed the shutdown order for quiescing demo (#219)
  Sources/HTTPServerWithQuiescingDemo/main.swift
Labels: needs-no-version-bump

#221 Fix NIOHTTPDecompression bug for multi-request channels
  Sources/NIOHTTPCompression/HTTPDecompression.swift
  Tests/NIOHTTPCompressionTests/HTTPResponseDecompressorTest.swift
Labels: patch-version-bump-only

#208 Enable automatic compression format detection
  Sources/NIOHTTPCompression/HTTPDecompression.swift
  Sources/NIOHTTPCompression/HTTPRequestDecompressor.swift
  Sources/NIOHTTPCompression/HTTPResponseDecompressor.swift
  Tests/NIOHTTPCompressionTests/HTTPRequestDecompressorTest.swift
  Tests/NIOHTTPCompressionTests/HTTPResponseDecompressorTest.swift
Labels: patch-version-bump-only
