Repository apple/swift-nio-extras, pull requests merged in 2024-12, with the labels that each got.

#203 Import HTTP resumable upload sample code
  .spi.yml
  Package.swift
  README.md
  Sources/NIOResumableUpload/HTTPResumableUpload.swift
  Sources/NIOResumableUpload/HTTPResumableUploadChannel.swift
  Sources/NIOResumableUpload/HTTPResumableUploadContext.swift
  Sources/NIOResumableUpload/HTTPResumableUploadHandler.swift
  Sources/NIOResumableUpload/HTTPResumableUploadProtocol.swift
  Sources/NIOResumableUploadDemo/main.swift
  Tests/NIOResumableUploadTests/NIOResumableUploadTests.swift
Labels: semver/minor

#240 Enable MemberImportVisibility check on all targets
  Package.swift
  Sources/NIOExtras/WritePCAPHandler.swift
  Sources/NIOSOCKS/Messages/SOCKSRequest.swift
Labels: semver/patch

#243 Update release.yml
  .github/release.yml
Labels: semver/none
