Repository apple/swift-nio-extras, pull requests merged in 2025-01, with the labels that each got.

#241 support h2 stream resets through user events
  Sources/NIOHTTPTypesHTTP2/HTTP2ToHTTPCodec.swift
  Tests/NIOHTTPTypesHTTP2Tests/NIOHTTPTypesHTTP2Tests.swift
Labels: 🆕 semver/minor

#245 Fix warnings
  Package.swift
  Sources/NIOExtras/HTTP1ProxyConnectHandler.swift
  Sources/NIOExtras/WritePCAPHandler.swift
  Sources/NIOExtrasPerformanceTester/HTTP1PCAPPerformanceTests.swift
  Sources/NIOExtrasPerformanceTester/HTTP1PerformanceTestFramework.swift
  Sources/NIOExtrasPerformanceTester/HTTP1RollingPCAPPerformanceTests.swift
  Sources/NIOExtrasPerformanceTester/PCAPPerformanceTest.swift
  Sources/NIOExtrasPerformanceTester/RollingPCAPPerformanceTest.swift
  Sources/NIOResumableUpload/HTTPResumableUploadChannel.swift
  Sources/NIOSOCKSClient/main.swift
  Sources/NIOWritePCAPDemo/main.swift
  Tests/NIOExtrasTests/DebugInboundEventsHandlerTest.swift
  Tests/NIOExtrasTests/DebugOutboundEventsHandlerTest.swift
  Tests/NIOExtrasTests/FixedLengthFrameDecoderTest.swift
  Tests/NIOExtrasTests/HTTP1ProxyConnectHandlerTests.swift
  Tests/NIOExtrasTests/JSONRPCFramingContentLengthHeaderDecoderTests.swift
  Tests/NIOExtrasTests/JSONRPCFramingContentLengthHeaderEncoderTests.swift
  Tests/NIOExtrasTests/LengthFieldBasedFrameDecoderTest.swift
  Tests/NIOExtrasTests/LengthFieldPrependerTest.swift
  Tests/NIOExtrasTests/LineBasedFrameDecoderTest.swift
  Tests/NIOExtrasTests/PCAPRingBufferTest.swift
  Tests/NIOExtrasTests/QuiescingHelperTest.swift
  Tests/NIOExtrasTests/RequestResponseHandlerTest.swift
  Tests/NIOExtrasTests/SynchronizedFileSinkTests.swift
  Tests/NIOExtrasTests/WritePCAPHandlerTest.swift
  Tests/NIOHTTPCompressionTests/HTTPRequestCompressorTest.swift
  Tests/NIOHTTPCompressionTests/HTTPRequestDecompressorTest.swift
  Tests/NIOHTTPCompressionTests/HTTPResponseCompressorTest.swift
  Tests/NIOHTTPCompressionTests/HTTPResponseDecompressorTest.swift
  Tests/NIOSOCKSTests/SOCKSServerHandshakeHandler+Tests.swift
  Tests/NIOSOCKSTests/SocksClientHandler+Tests.swift
Labels: 🔨 semver/patch

#244 Android support
  Sources/NIOExtras/DebugInboundEventsHandler.swift
  Sources/NIOExtras/DebugOutboundEventsHandler.swift
  Sources/NIOExtras/WritePCAPHandler.swift
  Sources/NIOSOCKS/Messages/SOCKSRequest.swift
  Tests/NIOExtrasTests/SynchronizedFileSinkTests.swift
  Tests/NIOExtrasTests/WritePCAPHandlerTest.swift
Labels: 🔨 semver/patch

#242 Responsiveness under Working Conditions
  .spi.yml
  Package.swift
  README.md
  Sources/NIOHTTPResponsiveness/HTTPDrippingDownloadHandler.swift
  Sources/NIOHTTPResponsiveness/HTTPReceiveDiscardHandler.swift
  Sources/NIOHTTPResponsiveness/ResponsivenessConfig.swift
  Sources/NIOHTTPResponsiveness/SimpleResponsivenessRequestMux.swift
  Tests/NIOHTTPResponsivenessTests/HTTPDrippingDownloadHandlerTests.swift
  Tests/NIOHTTPResponsivenessTests/HTTPResponsivenessTests.swift
Labels: 🆕 semver/minor

#246 CI use 6.1 nightlies
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#247 Avoid integer overrun in NIOHTTPResponsiveness
  Sources/NIOHTTPResponsiveness/ResponsivenessConfig.swift
Labels: 🔨 semver/patch
