Repository apple/swift-nio-extras, pull requests merged in 2025-04, with the labels that each got.

#257 Strict concurrency for NIOHTTPCompression
  Package.swift
  Sources/NIOHTTPCompression/HTTPCompression.swift
  Sources/NIOHTTPCompression/HTTPDecompression.swift
  Tests/NIOHTTPCompressionTests/HTTPResponseCompressorTest.swift
Labels: 🆕 semver/minor

#256 Strict concurrency for NIOSOCKS
  Package.swift
  Sources/NIOSOCKS/Messages/Errors.swift
  Tests/NIOSOCKSTests/SOCKSServerHandshakeHandler+Tests.swift
  Tests/NIOSOCKSTests/SocksClientHandler+Tests.swift
Labels: 🔨 semver/patch

#261 Strict concurrency for NIOHTTPResponsiveness and NIOHTTPResponsivenessTests
  Package.swift
  Sources/NIOHTTPResponsiveness/HTTPDrippingDownloadHandler.swift
  Sources/NIOHTTPResponsiveness/HTTPReceiveDiscardHandler.swift
  Sources/NIOHTTPResponsiveness/SimpleResponsivenessRequestMux.swift
  Sources/NIOResumableUploadDemo/main.swift
Labels: 🆕 semver/minor

#259 Strict concurrency for HTTPTypes and friends
  Package.swift
  Sources/NIOHTTPTypesHTTP1/HTTP1ToHTTPCodec.swift
  Sources/NIOHTTPTypesHTTP1/HTTPToHTTP1Codec.swift
  Sources/NIOHTTPTypesHTTP2/HTTP2ToHTTPCodec.swift
  Tests/NIOHTTPTypesHTTP1Tests/NIOHTTPTypesHTTP1Tests.swift
  Tests/NIOHTTPTypesHTTP2Tests/NIOHTTPTypesHTTP2Tests.swift
Labels: 🆕 semver/minor

#262 Strict concurrency for HTTPServerWithQuiescingDemo
  Package.swift
  Sources/HTTPServerWithQuiescingDemo/main.swift
Labels: semver/none

#263 Strict concurrency for NIOExtrasPerformanceTester
  Package.swift
  Sources/NIOExtrasPerformanceTester/HTTP1PCAPPerformanceTests.swift
  Sources/NIOExtrasPerformanceTester/HTTP1PerformanceTestFramework.swift
  Sources/NIOExtrasPerformanceTester/HTTP1RollingPCAPPerformanceTests.swift
Labels: semver/none

#258 Enable macOS CI on pull requests
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#265 Strict concurrency for NIOResumableUpload
  Package.swift
  Sources/NIOResumableUpload/HTTPResumableUpload.swift
  Sources/NIOResumableUpload/HTTPResumableUploadChannel.swift
  Sources/NIOResumableUpload/HTTPResumableUploadContext.swift
  Sources/NIOResumableUpload/HTTPResumableUploadHandler.swift
  Tests/NIOResumableUploadTests/NIOResumableUploadTests.swift
Labels: 🔨 semver/patch

#268 Enable Swift 6.1 jobs in CI
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none
