Repository apple/swift-nio-extras, pull requests merged in 2025-05, with the labels that each got.

#270 Drop Swift 5.9
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  Package.swift
  Tests/NIOExtrasTests/DebugInboundEventsHandlerTest.swift
  Tests/NIOExtrasTests/DebugOutboundEventsHandlerTest.swift
Labels: 🆕 semver/minor

#269 Add a `TimedCertificateReloader`
  Package.swift
  Sources/NIOCertificateReloading/CertificateReloader.swift
  Sources/NIOCertificateReloading/TimedCertificateReloader.swift
  Tests/NIOCertificateReloadingTests/TimedCertificateReloaderTests.swift
Labels: 🆕 semver/minor

#271 Update README.md Swift version table
  README.md
Labels: semver/none

#273 Support certificate chains from single PEM in `TimedCertificateReloader`
  Sources/NIOCertificateReloading/TimedCertificateReloader.swift
  Tests/NIOCertificateReloadingTests/TimedCertificateReloaderTests.swift
Labels: 🔨 semver/patch

#274 TimedCertificateReloader prevents non-self-signed certificates from b…
  Sources/NIOCertificateReloading/TimedCertificateReloader.swift
  Tests/NIOCertificateReloadingTests/TimedCertificateReloaderTests.swift
Labels: 🆕 semver/minor
